name: olist_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - asn1crypto=1.5.1
  - asttokens=3.0.1
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.1
  - cramjam=2.11.0
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - fastparquet=2025.12.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fsspec=2026.1.0
  - greenlet=3.2.4
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - icc_rt=2022.1.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.16
  - libjpeg-turbo=3.1.2
  - libllvm20=20.1.8
  - libopenjpeg=2.5.4
  - libparquet=22.0.0
  - libpng=1.6.50
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.11.2
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - nest-asyncio=1.6.0
  - nltk=3.9.2
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pathlib=1.0.1
  - pcre2=10.46
  - pg8000=1.31.5
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - psycopg2=2.9.10
  - psycopg2-binary=2.9.10
  - pthread-stubs=0.3
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qt-main=5.15.15
  - re2=2025.11.05
  - regex=2026.1.15
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - scramp=1.4.6
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlalchemy=2.0.43
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\Jesus\anaconda3\envs\olist_project
